GET http://localhost:4000/tasks

GET http://localhost:4000/tasks/2

POST http://localhost:4000/tasks
content-type: application/json

{
    "title": "tarea2",
    "description": "primera tarea",
    "project_id": 1,
}

DELETE http://localhost:4000/tasks/3

PUT http://localhost:4000/tasks/1
content-type: application/json

{
    "title": "tengo que hacer un frontend",
    "description": "usando react",
    "done": 1
}


### projects

GET http://localhost:4000/projects/


POST http://localhost:4000/projects/

content-type: application/json
{
    "name": "creacion de sistema para restaurantes",
    "priority": 1,
    "description": "tenemos una semana"
}
